---
- name: APPS | Update and Upgrade System
  apt:
    upgrade: yes
    update_cache: yes

- name: APPS | Install Apps
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - cockpit
    - nano
    - ntpdate
    - snmpd
    - snmp
    - git

- name: APPS | Enable Cockpit Service
  systemd:
    name: cockpit
    state: started
    enabled: yes

- name: GIT | Create User Infomration
  git_config:
    name: "{{ item.config_item }}"
    value: "{{ item.config_value }}"
    scope: global
  with_items: "{{ git_config }}"


- name: SSH | Create SSH git location
  git:
    repo: ssh://git@github.com/clinch123/SSH.git
    dest: "{{ ssh_git_location }}"
    key_file: "{{ ssh_git_key_file }}"
    update: yes
    force: yes
    clone: yes

- name: SSH | Remove Creds for Git URL
  command:
    cmd: git remote set-url origin https://github.com/clinch123/SSH.git
    chdir: "{{ ssh_git_location }}"

- name: SSH | Generate SSH Key
  openssh_keypair:
    path: "/home/{{ ssh_user }}/.ssh/rsa_{{ ansible_hostname }}"
    type: rsa
    owner: "{{ ssh_user }}"
    group: "{{ ssh_group }}"
    size: 2048
    state: present

- name: SSH | Fix Pub SSH Key
  file:
    path: /home/{{ ssh_user }}/.ssh/rsa_{{ ansible_hostname }}.pub
    owner: "{{ ssh_user }}"
    group: "{{ ssh_group }}"

- name: SSH | Add SSH Key to GitHub
  shell: 'curl -u "{{git_user}}:{{git_token}}" --data "{\"title\": \"TITLE\", \"key\": \"$(cat ~/.ssh/rsa_{{ ansible_hostname }}.pub)\"}" https://api.github.com/user/keys'

- name: SSH | Config Changes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: yes
  with_items: '{{ ssh_config_changes }}'

- name: SSH | Copy Pub SSH Key to known_hosts
  shell: echo /home/{{ ssh_user }}/.ssh/rsa_{{ ansible_hostname }}.pub >> {{ ssh_git_location }}/known_hosts

- name: SSH | Update Known Hosts on Git -- Add
  shell: "git add *"
  args:
    chdir: "{{ ssh_git_location }}"

- name: SSH | Update Known Hosts on Git -- Commit
  shell: git commit -m "Ansible Known Hosts Update"
  args:
    chdir: "{{ ssh_git_location }}"

- name: SSH | Update Known Hosts on Git -- Commit
  become: false
  shell: git push
  args:
    chdir: "{{ ssh_git_location }}"

- name: MONITORING | Configure SNMP
  lineinfile:
    path: /etc/snmp/snmpd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: yes
  with_items: '{{ snmp_configurations }}'
